#
# Module manifest for module 'cWinServer'
#
# Generated by: andrewb
#
# Generated on: 9/06/2015
@{
	ModuleVersion = '1.0'
	GUID = '90798d5f-9f2e-4af4-b9fd-79b4f67899fb'
	Author = 'andrewb'
	CompanyName = 'Unknown'
	Copyright = '(c) 2015 andrewb. All rights reserved.'
	Description = ''
	PowerShellVersion = '4.0'
	FunctionsToExport = @('Get-TargetResource','Set-TargetResource','Test-TargetResource')
}

